name: OpenClaw
options:
  bundleIdPrefix: ai.openclaw
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"

packages:
  OpenClawKit:
    path: ../shared
  Swabble:
    path: ../../Swabble

schemes:
  OpenClaw:
    shared: true
    build:
      targets:
        OpenClaw: all
    test:
      targets:
        - OpenClawTests

targets:
  OpenClaw:
    type: application
    platform: iOS
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
    sources:
      - path: Sources
    dependencies:
      - target: OpenClawShareExtension
        embed: true
      - package: OpenClawKit
      - package: OpenClawKit
        product: OpenClawChatUI
      - package: OpenClawKit
        product: OpenClawProtocol
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    settings:
      base:
        CODE_SIGN_IDENTITY: ""
        CODE_SIGN_ENTITLEMENTS: Sources/OpenClaw.entitlements
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
        PRODUCT_BUNDLE_IDENTIFIER: ai.openclaw.ios.sidestore
        PROVISIONING_PROFILE_SPECIFIER: ""
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: OpenClaw
        CFBundleIconName: AppIcon
        CFBundleURLTypes:
          - CFBundleURLName: ai.openclaw.ios
            CFBundleURLSchemes:
              - openclaw
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes:
          - audio
          - remote-notification
        BGTaskSchedulerPermittedIdentifiers:
          - ai.openclaw.ios.bgrefresh
        NSLocalNetworkUsageDescription: OpenClaw discovers and connects to your OpenClaw gateway on the local network.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: true
        NSBonjourServices:
          - _openclaw-gw._tcp
        NSCameraUsageDescription: OpenClaw can capture photos or short video clips when requested via the gateway.
        NSLocationWhenInUseUsageDescription: OpenClaw uses your location when you allow location sharing.
        NSLocationAlwaysAndWhenInUseUsageDescription: OpenClaw can share your location in the background when you enable Always.
        NSMicrophoneUsageDescription: OpenClaw needs microphone access for voice wake.
        NSSpeechRecognitionUsageDescription: OpenClaw uses on-device speech recognition for voice wake.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  OpenClawShareExtension:
    type: app-extension
    platform: iOS
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
    sources:
      - path: ShareExtension
    dependencies:
      - package: OpenClawKit
    settings:
      base:
        CODE_SIGN_IDENTITY: ""
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
        PRODUCT_BUNDLE_IDENTIFIER: ai.openclaw.ios.sidestore.share
        PROVISIONING_PROFILE_SPECIFIER: ""
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
    info:
      path: ShareExtension/Info.plist
      properties:
        CFBundleDisplayName: OpenClaw Share
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).ShareViewController"
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsText: true
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
              NSExtensionActivationSupportsImageWithMaxCount: 10
              NSExtensionActivationSupportsMovieWithMaxCount: 1

  OpenClawTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: OpenClaw
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.openclaw.ios.tests
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/OpenClaw.app/OpenClaw"
        BUNDLE_LOADER: "$(TEST_HOST)"
    info:
      path: Tests/Info.plist
      properties:
        CFBundleDisplayName: OpenClawTests
        CFBundleShortVersionString: "2026.2.21"
        CFBundleVersion: "20260220"
